name: BinaryFire
favicon: null
layout_spectrum: 0.9761153277941048
typography_spectrum: 0.8651312452275306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9525321684777737
  lightness: 0.7913886476308107
  saturation: 0.08734661526978016
  rhythmicContrast: 0.0690239043906331
purpose: []
